dataset:
  storage_folder: DATA_MLWIZ/REDDIT-MULTI-5K
  dataset_class: dataset.TUDatasetInterface
  data_splits_file: DATA_SPLITS_MLWIZ/REDDIT-MULTI-5K/TUDatasetInterface/TUDatasetInterface_outer10_inner1.splits
resources:
  device: cuda
  max_cpus: 8
  max_gpus: 4
  gpus_per_task: 0.5
  sync_batchnorm: false
reproducibility:
  seed: 42
data_loading:
  dataset_getter: provider.DataProvider
  data_loader:
    class_name: torch_geometric.loader.DataLoader
    args:
      num_workers: 1
      pin_memory: true
experiment:
  result_folder: RESULTS_MLWIZ
  exp_name: sup_model_embedding_classification_SOCIAL_REDDIT-MULTI-5K_mlwiz_refactored
  experiment: mlwiz.experiment.Experiment
  model_selection_criteria:
  - metric: main_score
    direction: max
  evaluate_every: 1
  risk_assessment_training_runs: 3
  model_selection_training_runs: 1
grid:
  model: model.SupGSPN
  checkpoint: true
  shuffle: true
  batch_size: 32
  epochs: 500
  convolution_class: model.GSPNBaseConv
  emission_class: model.GSPNGaussianEmission
  num_mixtures:
  - 20
  - 40
  num_graph_mixtures:
  - 32
  - 128
  num_layers:
  - 5
  - 10
  - 20
  global_readout:
  - sum
  - mean
  optimizer:
  - class_name: mlwiz.training.callback.optimizer.Optimizer
    args:
      optimizer_class_name: torch.optim.Adam
      lr: 0.01
      accumulate_gradients: false
  scheduler: null
  loss:
  - class_name: mlwiz.training.callback.metric.AdditiveLoss
    args:
      classification: mlwiz.training.callback.metric.MulticlassClassification
      data_likelihood: metric.GSPNNodeLogLikelihood
  scorer:
  - class_name: mlwiz.training.callback.metric.MultiScore
    args:
      main_scorer: mlwiz.training.callback.metric.MulticlassAccuracy
      data_likelihood: metric.GSPNNodeLogLikelihood
  readout: null
  engine: mlwiz.training.engine.TrainingEngine
  gradient_clipper: null
  early_stopper:
  - class_name: mlwiz.training.callback.early_stopping.PatienceEarlyStopper
    args:
      patience: 50
      monitor: validation_main_score
      mode: max
      checkpoint: true
  plotter: mlwiz.training.callback.plotter.Plotter
