splitter:
  splits_folder: DATA_SPLITS_MLWIZ/REDDIT-MULTI-5K
  class_name: migration.PreservedSplitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: true
    shuffle: true
    inner_val_ratio: 0.1
    outer_val_ratio: 0.1
    test_ratio: 0.1
    legacy_splits_file: DATA_SPLITS/COLLABORATIVE_DEGREE/REDDIT-MULTI-5K/REDDIT-MULTI-5K_outer10_inner1.splits
dataset:
  class_name: dataset.TUDatasetInterface
  args:
    root: DATA
    name: REDDIT-MULTI-5K
    storage_folder: DATA_MLWIZ/REDDIT-MULTI-5K
    seed: 42
    transform_train:
      class_name: transform.Compose
      args:
        transforms:
        - class_name: transform.Degree
          args:
            in_degree: true
    transform_eval:
      class_name: transform.Compose
      args:
        transforms:
        - class_name: transform.Degree
          args:
            in_degree: true
